# Generated by Django 5.1.6 on 2025-12-20 20:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agriculteur',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('phoneNum', models.IntegerField(unique=True)),
                ('numero_carte_fellah', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id', 'subdivision_id'],
            },
        ),
        migrations.CreateModel(
            name='Espece',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubDivision',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id', 'wilaya_id'],
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('nom', models.CharField(max_length=15)),
                ('prenom', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNum', models.IntegerField(blank=True, null=True, unique=True)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Exploitation',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('situation', models.CharField(max_length=500)),
                ('longtitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('agriculteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploitations', to='api.agriculteur')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commune')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('annee', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sup_labouree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sup_emblavee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sup_sinsitree', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sup_recoltee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sup_deserbee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prev_de_production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('engrais_de_fond', models.DecimalField(decimal_places=2, max_digits=10)),
                ('engrais_de_couverture', models.DecimalField(decimal_places=2, max_digits=10)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.espece')),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exploitation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('model', models.CharField(max_length=15)),
                ('create', models.BooleanField(default=False)),
                ('retrieve', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=False)),
                ('destroy', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='commune',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.subdivision'),
        ),
        migrations.CreateModel(
            name='UserSubdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subdivision')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserWilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wilaya')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='subdivision',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.wilaya'),
        ),
        migrations.CreateModel(
            name='Objectif',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('annee', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objectif_production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('espece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.espece')),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wilaya')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='exploitation',
            index=models.Index(fields=['commune'], name='api_exploit_commune_232ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='exploitation',
            index=models.Index(fields=['agriculteur'], name='api_exploit_agricul_5d37a8_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelle',
            index=models.Index(fields=['espece', 'annee'], name='api_parcell_espece__e09388_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelle',
            index=models.Index(fields=['exploitation', 'annee'], name='api_parcell_exploit_4c7239_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelle',
            index=models.Index(fields=['annee'], name='api_parcell_annee_5ebfef_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelle',
            index=models.Index(fields=['espece'], name='api_parcell_espece__ac3203_idx'),
        ),
        migrations.AddIndex(
            model_name='commune',
            index=models.Index(fields=['subdivision'], name='api_commune_subdivi_6a7439_idx'),
        ),
        migrations.AddIndex(
            model_name='subdivision',
            index=models.Index(fields=['wilaya'], name='api_subdivi_wilaya__ba9e37_idx'),
        ),
        migrations.AddIndex(
            model_name='objectif',
            index=models.Index(fields=['wilaya', 'annee'], name='api_objecti_wilaya__4ddbb5_idx'),
        ),
        migrations.AddIndex(
            model_name='objectif',
            index=models.Index(fields=['espece', 'annee'], name='api_objecti_espece__2ea664_idx'),
        ),
        migrations.AddIndex(
            model_name='objectif',
            index=models.Index(fields=['wilaya', 'espece'], name='api_objecti_wilaya__3b29af_idx'),
        ),
    ]
