# Generated by Django 5.1.6 on 2025-05-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='model',
            field=models.CharField(max_length=15),
        ),
    ]
